# Generated by Django 3.1.5 on 2021-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.CharField(max_length=64)),
                ('date_of_death', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('gender', models.BooleanField()),
                ('native_language', models.CharField(max_length=64)),
            ],
        ),
    ]
