# Generated by Django 3.1.5 on 2021-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210126_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=64)),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
