# Generated by Django 3.1.5 on 2021-03-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='charfield',
            new_name='category',
        ),
    ]
