# Generated by Django 3.1.5 on 2021-03-26 14:44

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_requestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default='books/none/book_none.jpg', null=True, upload_to=books.models.book_upload_cover),
        ),
    ]
