# Generated by Django 3.1.5 on 2021-03-26 15:01

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(default=None, null=True, upload_to=books.models.book_upload_cover),
        ),
    ]
